services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - jellyfin_config:/config
      - jellyfin_cache:/cache
      - movies:/movies
      - series:/series
    networks:
      - media_net
    ports:
      - 8096:8096

  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=000
      - TZ=${TZ}
    volumes:
      - qbittorrent_config:/config
      - movies:/movies
      - series:/series
    networks:
      - media_net
    ports:
      - 8080:8080

  nzbget:
    image: linuxserver/nzbget:latest
    container_name: nzbget
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - nzbget_config:/config
      - nzbget_queue:/queue
      - movies:/movies
      - series:/series
    networks:
      - media_net
    ports:
      - 6789:6789

  prowlarr:
    image: linuxserver/prowlarr:nightly
    container_name: prowlarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_DIR}/prowlarr/config:/config
    networks:
      - media_net
    ports:
      - 9696:9696

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_DIR}/sonarr/config:/config
      - movies:/movies
      - series:/series
    networks:
      - media_net
    ports:
      - 8989:8989

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    restart: unless-stopped
    environment:
      - JELLYFIN_API_URL=http://jellyfin:8096
      - JELLYFIN_API_KEY=${JELLYFIN_API_KEY}
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - jellyseerr_config:/app/config
      - movies:/movies
      - series:/series
    networks:
      - media_net
    ports:
      - 5055:5055

  radarr:
    image: linuxserver/radarr:nightly
    container_name: radarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_DIR}/radarr/config:/config
      - movies:/movies
      - series:/series
    networks:
      - media_net
    ports:
      - 7878:7878

  ip-checker:
    build:
      context: ./ip-checker
    container_name: ip-checker
    restart: unless-stopped
    ports:
      - 5000:5000
    networks:
      - media_net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./ip-checker/templates:/app/templates

volumes:
  qbittorrent_config:
    driver_opts:
      type: "nfs"
      o: "addr=${NFS_SERVER_IP},rw,nfsvers=4"
      device: ":/qbittorrent_config"
  jellyfin_config:
    driver_opts:
      type: "nfs"
      o: "addr=${NFS_SERVER_IP},rw,nfsvers=4"
      device: ":/jellyfin_config"
  jellyfin_cache:
    driver_opts:
      type: "nfs"
      o: "addr=${NFS_SERVER_IP},rw,nfsvers=4"
      device: ":/jellyfin_cache"
  nzbget_config:
    driver_opts:
      type: "nfs"
      o: "addr=${NFS_SERVER_IP},rw,nfsvers=4"
      device: ":/nzbget_config"
  nzbget_queue:
    driver_opts:
      type: "nfs"
      o: "addr=${NFS_SERVER_IP},rw,nfsvers=4"
      device: ":/nzbget_queue"

  jellyseerr_config:
    driver_opts:
      type: "nfs"
      o: "addr=${NFS_SERVER_IP},rw,nfsvers=4"
      device: ":/jellyseerr_config"
  movies:
    driver_opts:
      type: "nfs"
      o: "addr=${NFS_SERVER_IP},rw,nfsvers=4"
      device: ":/movies"
  series:
    driver_opts:
      type: "nfs"
      o: "addr=${NFS_SERVER_IP},rw,nfsvers=4"
      device: ":/series"

networks:
  media_net:
    driver: bridge
